server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/el?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: asdert123

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    database-platform: org.hibernate.dialect.MySQLDialect



    mvc:
      static-path-pattern: /**

    devtools:
      livereload:
        enabled: true
      restart:
        additional-paths: static/**


    jackson:
      date-format: yyyy-MM-dd HH:mm:ss

